[package]
name = "azuuu/weave"
description = "Weave is a robust and evergrowing backend framework for Roblox."
version = "0.1.0-Iris"
registry = "https://github.com/UpliftGames/wally-index"
authors = ["AzurisDev", "Iris Interactive Tech Team"]
realm = "shared"

[dependencies]
